export default games = [
    {
        id: 1,
        title: "Manic Miner",
        teaser: "Bespectacled man runs-amok in someone else's house",
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veniam illo earum animi doloribus",
        rating: 4.8,
        category: ["Action", "Indie"],
        age: "12+,",
        cover: require("./assets/a2.png"),
        screenshots:[
            require("./assets/a1.png"),
            require("./assets/a1.png"),
            require("./assets/a1.png"),
            require("./assets/a1.png"),
            require("./assets/a1.png"),
        ],
        backgroundColor:"#824571",
    },
    {
        id: 2,
        title: "Manic Miner",
        teaser: "Bespectacled man runs-amok in someone else's house",
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veniam illo earum animi doloribus",
        rating: 4.8,
        category: ["Action", "Indie"],
        age: "12+,",
        cover: require("./assets/a2.png"),
        screenshots:[
            require("./assets/a1.png"),
            require("./assets/a1.png"),
            require("./assets/a1.png"),
            require("./assets/a1.png"),
            require("./assets/a1.png"),
        ],
        backgroundColor:"#824571",
    },
    {
        id: 3,
        title: "Manic Miner",
        teaser: "Bespectacled man runs-amok in someone else's house",
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veniam illo earum animi doloribus",
        rating: 4.8,
        category: ["Action", "Indie"],
        age: "12+,",
        cover: require("./assets/a2.png"),
        screenshots:[
            require("./assets/a1.png"),
            require("./assets/a1.png"),
            require("./assets/a1.png"),
            require("./assets/a1.png"),
            require("./assets/a1.png"),
        ],
        backgroundColor:"#824571",
    },

]